#!/bin/bash

# clear build directory (also clears CMake cache)
BUILD_DIR=$1
rm -rf $BUILD_DIR
mkdir $BUILD_DIR
cd $BUILD_DIR

# build configuration
build_options=(
    -DCMAKE_BUILD_TYPE=Debug

    -DVRN_OPENGL_COMPATIBILITY_PROFILE=OFF

    -DVRN_BUILD_VOREENVE=ON
    -DVRN_BUILD_VOREENTOOL=ON
    -DVRN_BUILD_SIMPLEGLUT=ON
    -DVRN_BUILD_SIMPLEQT=ON
    -DVRN_BUILD_TESTAPPS=ON
    -DVRN_BUILD_ITK_WRAPPER=ON

    -DVRN_MODULE_ADVANCEDLIGHTING=OFF
    -DVRN_MODULE_BASE=OFF
    -DVRN_MODULE_CONNEXE=OFF
    -DVRN_MODULE_DEPRECATED=OFF
    -DVRN_MODULE_DEVIL=OFF
    -DVRN_MODULE_DYNAMICGLSL=OFF
    -DVRN_MODULE_FFMPEG=OFF
    -DVRN_MODULE_FLOWREEN=OFF
    -DVRN_MODULE_GDCM=OFF
    -DVRN_MODULE_ITK=OFF
    -DVRN_MODULE_ITK_GENERATED=OFF
    -DVRN_MODULE_OPENCL=OFF
    -DVRN_MODULE_OPENMP=OFF
    -DVRN_MODULE_PLOTTING=OFF
    -DVRN_MODULE_POI=OFF
    -DVRN_MODULE_PVM=OFF
    -DVRN_MODULE_PYTHON=OFF
    -DVRN_MODULE_RANDOMWALKER=OFF
    -DVRN_MODULE_SEGY=OFF
    -DVRN_MODULE_SIMDRAYCASTER=OFF
    -DVRN_MODULE_STAGING=OFF
    -DVRN_MODULE_STEREOSCOPY=OFF
    -DVRN_MODULE_SURFACE=OFF
    -DVRN_MODULE_TIFF=OFF
    -DVRN_MODULE_VOLUMELABELING=OFF
    -DVRN_MODULE_ZIP=OFF
)
cmake "${build_options[@]}" ../voreen

N_CORES=$(nproc)
# start build once again to make errors (if any) more readable
nice make -j$N_CORES || make
